"""One lifecycle shared by every emergency interface."""

from enum import StrEnum


class EmergencyStatus(StrEnum):
    CREATED = "CREATED"
    DISPATCHING = "DISPATCHING"
    AMBULANCE_ASSIGNED = "AMBULANCE_ASSIGNED"
    DRIVER_NOTIFIED = "DRIVER_NOTIFIED"
    EN_ROUTE_TO_PATIENT = "EN_ROUTE_TO_PATIENT"
    ARRIVED_AT_PATIENT = "ARRIVED_AT_PATIENT"
    PATIENT_ONBOARD = "PATIENT_ONBOARD"
    HOSPITAL_SELECTION = "HOSPITAL_SELECTION"
    HOSPITAL_ASSIGNED = "HOSPITAL_ASSIGNED"
    HOSPITAL_ACCEPTED = "HOSPITAL_ACCEPTED"
    GREEN_CORRIDOR_ACTIVE = "GREEN_CORRIDOR_ACTIVE"
    EN_ROUTE_TO_HOSPITAL = "EN_ROUTE_TO_HOSPITAL"
    ARRIVED_AT_HOSPITAL = "ARRIVED_AT_HOSPITAL"
    PATIENT_HANDOVER = "PATIENT_HANDOVER"
    COMPLETED = "COMPLETED"
    HOSPITAL_REJECTED = "HOSPITAL_REJECTED"
    REROUTING = "REROUTING"
    ROAD_BLOCKED = "ROAD_BLOCKED"
    CRITICAL_ESCALATION = "CRITICAL_ESCALATION"
    CANCELLED = "CANCELLED"


TERMINAL = {"COMPLETED", "CANCELLED"}
TRANSITIONS = {
    "CREATED": {"DISPATCHING", "CANCELLED"},
    "DISPATCHING": {"AMBULANCE_ASSIGNED", "CRITICAL_ESCALATION", "CANCELLED"},
    "AMBULANCE_ASSIGNED": {"DRIVER_NOTIFIED"},
    "DRIVER_NOTIFIED": {"EN_ROUTE_TO_PATIENT", "CANCELLED"},
    "EN_ROUTE_TO_PATIENT": {
        "DISPATCHING",
        "ARRIVED_AT_PATIENT",
        "REROUTING",
        "ROAD_BLOCKED",
        "CANCELLED",
    },
    "ARRIVED_AT_PATIENT": {"PATIENT_ONBOARD", "CANCELLED"},
    "PATIENT_ONBOARD": {"HOSPITAL_SELECTION"},
    "HOSPITAL_SELECTION": {"HOSPITAL_ASSIGNED", "CRITICAL_ESCALATION"},
    "HOSPITAL_ASSIGNED": {"HOSPITAL_ACCEPTED", "HOSPITAL_REJECTED"},
    "HOSPITAL_ACCEPTED": {
        "GREEN_CORRIDOR_ACTIVE",
        "EN_ROUTE_TO_HOSPITAL",
        "HOSPITAL_REJECTED",
    },
    "GREEN_CORRIDOR_ACTIVE": {"EN_ROUTE_TO_HOSPITAL", "HOSPITAL_REJECTED"},
    "EN_ROUTE_TO_HOSPITAL": {
        "ARRIVED_AT_HOSPITAL",
        "REROUTING",
        "ROAD_BLOCKED",
        "HOSPITAL_REJECTED",
    },
    "HOSPITAL_REJECTED": {"HOSPITAL_SELECTION"},
    "REROUTING": {"EN_ROUTE_TO_PATIENT", "EN_ROUTE_TO_HOSPITAL", "ROAD_BLOCKED"},
    "ROAD_BLOCKED": {"REROUTING", "HOSPITAL_REJECTED", "CANCELLED"},
    "CRITICAL_ESCALATION": {"DISPATCHING", "HOSPITAL_SELECTION", "CANCELLED"},
    "ARRIVED_AT_HOSPITAL": {"PATIENT_HANDOVER"},
    "PATIENT_HANDOVER": {"COMPLETED"},
}

for _state in EmergencyStatus:
    if _state.value not in TERMINAL:
        TRANSITIONS.setdefault(_state.value, set()).add("CANCELLED")
