import { env } from 'cloudflare:workers';
import {seed,tick,State,Role} from '../features/engine';
export function db(){if(!env.DB)throw Error('Emergency database unavailable. Please retry.');return env.DB;}
export async function session(req:Request){const token=req.headers.get('authorization')?.match(/^Bearer\s+(.+)$/i)?.[1]||(req.headers.get('cookie')||'').match(/aegis_session=([^;]+)/)?.[1];if(!token)return null;const claims=await verifyToken(token);if(!claims)return null;return await db().prepare('SELECT users.id,users.name,users.email,users.role FROM sessions JOIN users ON users.id=sessions.user_id WHERE sessions.id=? AND sessions.expires>?').bind(claims.jti,Date.now()).first<{id:string;name:string;email:string;role:Role}>();}
export function workspace(u:{id:string}|null){return !u||u.id.startsWith('demo-')?'city':u.id;}
export async function readState(key='city'){await db().prepare('INSERT OR IGNORE INTO simulation (id,revision,data) VALUES (?,0,?)').bind(key,JSON.stringify(initialState(key))).run();const row=await db().prepare('SELECT data,revision FROM simulation WHERE id=?').bind(key).first<{data:string;revision:number}>();return {state:JSON.parse(row!.data) as State,revision:row!.revision};}
function initialState(key:string){const s=seed();if(key!=='city'){s.emergencies=[];s.notifications=[];s.ambulances.forEach(a=>a.status='AVAILABLE');s.hospitals.forEach(h=>{h.resources.forEach(r=>{if(r.emergencyId){r.status='AVAILABLE';delete r.emergencyId;}});h.icu=h.resources.filter(r=>r.status==='AVAILABLE').length;});s.signals.forEach(j=>{j.mode='NORMAL';j.state='RED';});}return s;}
export async function mutate(fn:(s:State)=>void,user?:{id:string;role:string},action='monitor.tick',key=workspace(user||null)){for(let i=0;i<5;i++){const {state,revision}=await readState(key);const before=JSON.stringify(state);fn(state);const data=JSON.stringify(state);if(data===before)return {...state,revision};const results=await db().batch([db().prepare('UPDATE simulation SET data=?,revision=revision+1 WHERE id=? AND revision=?').bind(data,key,revision),db().prepare('INSERT INTO audit (id,user_id,role,action,emergency_id,before,after,created_at) SELECT ?,?,?,?,?,?,?,? WHERE changes()=1').bind(crypto.randomUUID(),user?.id||'system',user?.role||'Monitoring Agent',action,state.emergencies[0]?.id||null,before,data,Date.now())]);if(results[0].meta.changes)return {...state,revision:revision+1};}throw Error('Another operator updated this case. Please retry.');}
export async function stateFor(req:Request){const u=await session(req);let s=await mutate(tick,undefined,'monitor.tick',workspace(u));if(!u){s={...s,emergencies:s.emergencies.filter(e=>e.owner==='demo').map(e=>({...e,name:'Simulated patient',observations:[]})),notifications:s.notifications.filter(n=>!n.message.includes('AEG-2026-')||n.message.includes('1042'))};}else if(u.role==='Citizen')s={...s,emergencies:s.emergencies.filter(e=>e.owner===u.id)};else if(u.role==='Ambulance Driver'||u.role==='Paramedic')s={...s,emergencies:s.emergencies.filter(e=>e.ambulance==='A-07')};else if(u.role==='Hospital Staff')s={...s,emergencies:s.emergencies.filter(e=>e.hospital==='H-B')};else if(u.role==='Traffic Officer')s={...s,emergencies:s.emergencies.map(e=>({...e,name:'Protected patient',vitals:{hr:0,spo2:0,bp:'—',consciousness:'Protected',bleeding:'Protected'},observations:[]}))};return {state:s,user:u};}
export function error(e:unknown,status=400){console.error(e instanceof Error?e.message:e);return Response.json({error:e instanceof Error?e.message:'Unable to complete request'},{status});}
export function allowedOrigin(origin:string| null,requestUrl?:string){if(!origin)return null;if(origin===new URL(requestUrl||origin).origin)return origin;return /^(?:https?:\/\/(?:localhost|127(?:\.\d{1,3}){3}|10(?:\.\d{1,3}){3}|192\.168(?:\.\d{1,3}){2}|172\.(?:1[6-9]|2[0-9]|3[01])(?:\.\d{1,3}){2})(?::\d+)?|exp(?:\+aegis)?:\/\/[a-z0-9.-]+(?::\d+)?|aegis:\/\/[a-z0-9.-]+)$/i.test(origin)?origin:null;}
export function validOrigin(req:Request){const origin=req.headers.get('origin');if(origin&&!allowedOrigin(origin,req.url))throw Error('Invalid request origin');}
export function cors(req:Request){const origin=allowedOrigin(req.headers.get('origin'),req.url);return origin?{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Credentials':'true','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Max-Age':'600','Vary':'Origin'}:{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Authorization, Content-Type'};}
export async function limit(req:Request){const key=(req.headers.get('cf-connecting-ip')||'local')+':'+Math.floor(Date.now()/60000);await db().prepare('INSERT INTO rate_limits (id,count,expires) VALUES (?,1,?) ON CONFLICT(id) DO UPDATE SET count=count+1').bind(key,Date.now()+60000).run();const r=await db().prepare('SELECT count FROM rate_limits WHERE id=?').bind(key).first<{count:number}>();if(r!.count>40)throw Error('Too many requests. Try again in a minute.');}
export async function hash(password:string,salt:string){const key=await crypto.subtle.importKey('raw',new TextEncoder().encode(password),'PBKDF2',false,['deriveBits']);const bits=await crypto.subtle.deriveBits({name:'PBKDF2',salt:new TextEncoder().encode(salt),iterations:100000,hash:'SHA-256'},key,256);return Array.from(new Uint8Array(bits)).map(n=>n.toString(16).padStart(2,'0')).join('');}

function encode(data:Uint8Array){return btoa(String.fromCharCode(...data)).replaceAll('+','-').replaceAll('/','_').replaceAll('=','');}
function decode(value:string){return Uint8Array.from(atob(value.replaceAll('-','+').replaceAll('_','/')),c=>c.charCodeAt(0));}
async function signingKey(){const bytes=crypto.getRandomValues(new Uint8Array(32));await db().prepare('INSERT OR IGNORE INTO signing_keys (id,secret) VALUES (?,?)').bind('jwt',encode(bytes)).run();const row=await db().prepare('SELECT secret FROM signing_keys WHERE id=?').bind('jwt').first<{secret:string}>();return crypto.subtle.importKey('raw',decode(row!.secret),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
export async function makeToken(sub:string,jti:string){const header=encode(new TextEncoder().encode(JSON.stringify({alg:'HS256',typ:'JWT'})));const body=encode(new TextEncoder().encode(JSON.stringify({sub,jti,iat:Math.floor(Date.now()/1000),exp:Math.floor(Date.now()/1000)+86400})));const text=header+'.'+body;const signature=await crypto.subtle.sign('HMAC',await signingKey(),new TextEncoder().encode(text));return text+'.'+encode(new Uint8Array(signature));}
export async function verifyToken(token:string):Promise<{sub:string;jti:string;exp:number}|null>{try{const parts=token.split('.');if(parts.length!==3)return null;const header=JSON.parse(new TextDecoder().decode(decode(parts[0])));if(header.alg!=='HS256'||header.typ!=='JWT')return null;const valid=await crypto.subtle.verify('HMAC',await signingKey(),decode(parts[2]),new TextEncoder().encode(parts[0]+'.'+parts[1]));if(!valid)return null;const claims=JSON.parse(new TextDecoder().decode(decode(parts[1])));return typeof claims.jti==='string'&&typeof claims.sub==='string'&&claims.exp>Date.now()/1000?claims:null;}catch{return null;}}

export function apiError(req:Request,e:unknown,status=400){const result=error(e,status);const headers=new Headers(result.headers);for(const [k,v]of Object.entries(cors(req)))headers.set(k,v);return new Response(result.body,{status:result.status,headers});}
