import {Activity,ChevronRight,Clock} from 'lucide-react';
import {Area,AreaChart,CartesianGrid,ResponsiveContainer,Tooltip,XAxis,YAxis} from 'recharts';
import type {Metrics,RoadEvent} from '../types';
import {timestamp} from '../services/api';
export function RoadTimeline({timeline,events,onSeek}:{timeline:Metrics[];events:RoadEvent[];onSeek:(time:number)=>void}){
 return <section className="timeline-panel surface"><div className="section-title"><div><Clock size={17}/><h2>One road. Every change.</h2></div><span>{events.length?`${events.length} observations`:'Your road’s story will appear here'}</span></div>
 {timeline.length>0?<div className="timeline-chart"><div className="chart-legend"><i/> Traffic intensity <i className="health"/> Road health</div><ResponsiveContainer width="100%" height={180}><AreaChart data={timeline}><defs><linearGradient id="trafficGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#6de9cc" stopOpacity={.23}/><stop offset="100%" stopColor="#6de9cc" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="#20313c" vertical={false}/><XAxis dataKey="timestampSeconds" tickFormatter={timestamp} stroke="#7b919c" fontSize={12}/><YAxis yAxisId="traffic" domain={[0,1]} tickFormatter={n=>`${Math.round(n*100)}%`} stroke="#7b919c" fontSize={12}/><YAxis yAxisId="health" domain={[0,100]} hide/><Tooltip labelFormatter={n=>timestamp(Number(n))} contentStyle={{background:'#13212b',border:'1px solid #334653',borderRadius:8}}/><Area isAnimationActive={false} yAxisId="traffic" type="monotone" dataKey="trafficScore" name="Traffic score" stroke="#6de9cc" fill="url(#trafficGradient)"/><Area isAnimationActive={false} yAxisId="health" type="monotone" dataKey="roadHealthScore" name="Road health" stroke="#e4b774" fill="transparent"/></AreaChart></ResponsiveContainer></div>:<div className="timeline-empty"><Activity size={25}/><span>Traffic changes, persistent evidence and unusual events — connected in one timeline.</span></div>}
 {events.length>0&&<div className="event-list">{events.map(event=><button key={event.eventId} className={`event ${event.severity==='HIGH'?'urgent':''}`} onClick={()=>onSeek(event.timestampSeconds)}><span className="event-point"/><time>{timestamp(event.timestampSeconds)}</time><div><b>{event.title||event.eventType.replaceAll('_',' ')}</b>{event.confidence!=null&&<small>Detector score {Math.round(event.confidence*100)}% · review evidence</small>}</div><ChevronRight size={16}/></button>)}</div>}
 </section>;
}
