import {ArrowUpRight,BrainCircuit,Check,ChevronDown,MoveUpRight,Shield,TriangleAlert} from 'lucide-react';
import type {Intelligence,Metrics} from '../types';
import {percentage} from '../services/api';
export function Understanding({intelligence,metrics,busy}:{intelligence?:Intelligence;metrics?:Metrics;busy:boolean}){
 return <aside className="understanding surface"><div className="section-title"><div><BrainCircuit size={18}/><h2>AI understanding</h2></div><span className="tiny-tag">ROAD BRAIN</span></div>
 {intelligence?<><div className="observation"><div className="small-label">CURRENT SITUATION</div><h3>{intelligence.condition}</h3><p>{intelligence.understanding}</p><div className="trend"><MoveUpRight size={15}/><span>Traffic trend</span><b>{intelligence.trend}</b></div>{intelligence.trafficProjection&&<p className="projection">60s traffic-score projection: {Math.round(intelligence.trafficProjection.projectedTrafficScore*100)}%<small>Linear trend extrapolation · experimental, not a probability</small></p>}</div>
 <div className="findings"><div className="small-label">WHAT THE CAMERA SUPPORTS</div>{intelligence.findings.map((finding,index)=><div className={`finding ${finding.kind==='hazard'||finding.kind==='incident'?'warning':''}`} key={`${finding.kind}-${index}`}><span className="finding-icon">{finding.kind==='hazard'||finding.kind==='incident'?<TriangleAlert size={15}/>:<Check size={15}/>}</span><div><b>{finding.title}</b><p>{finding.description}</p>{finding.confidence!=null&&<small>Detector score {Math.round(finding.confidence*100)}%{finding.experimental?' · Experimental':''}</small>}{finding.experimental&&finding.confidence==null&&<small>Experimental · verify in video</small>}</div></div>)}</div>
 <div className="scores"><div className="score"><span>ROAD HEALTH</span><b>{intelligence.roadHealthScore}<small>/100</small></b><div className="score-track"><i style={{width:`${intelligence.roadHealthScore}%`}}/></div></div><div className="score"><span>EMERGENCY ACCESS</span><b>{intelligence.emergencyAccessScore}<small>/100</small></b><div className="score-track"><i style={{width:`${intelligence.emergencyAccessScore}%`}}/></div></div></div><div className="score-note">Experimental visual estimates · physical ambulance clearance is unresolved.</div>
 <div className="recommendation"><Shield size={18}/><div><span>AEGIS RECOMMENDATION</span><b>{intelligence.recommendation}</b></div></div>
 <details className="evidence-details"><summary>Why this conclusion? <ChevronDown size={14}/></summary><p>{intelligence.cause==='UNRESOLVED'?'The cause of current road conditions is unresolved.':intelligence.cause}</p>{intelligence.sceneGraph.map((edge,index)=><div className="graph-edge" key={index}><span>{edge.from}</span><ArrowUpRight size={13}/><span>{edge.relation} {edge.to}</span></div>)}<div className="penalties">{Object.entries(intelligence.scorePenalties).filter(([,value])=>value>0).map(([key,value])=><div key={key}><span>{key.replaceAll(/([A-Z])/g,' $1')}</span><b>−{value}</b></div>)}</div><p>{intelligence.confidenceType}</p>{intelligence.coverage.gaps.map(gap=><p key={gap}>{gap}</p>)}</details>
 </>:<div className="brain-empty"><div className={`brain-orbit ${busy?'thinking':''}`}><BrainCircuit size={36}/></div><div className="small-label">{busy?'OBSERVING THE ROAD':'ONE CAMERA. ONE AI.'}</div><h3>{busy?'Connecting the evidence.':'A complete picture starts here.'}</h3><p>{busy?'The road brain is combining the road region, vehicles, motion and changes over time.':'Upload a road video. OmniVision watches the scene, follows what changes, and explains what the evidence means.'}</p><div className="brain-steps"><span><Check size={13}/> Automatic road region</span><span><Check size={13}/> Vehicles & motion</span><span><Check size={13}/> Persistent scene evidence</span><span><Check size={13}/> One connected conclusion</span></div>{metrics&&<p>{metrics.vehicleCount} vehicles observed · {percentage(metrics.roadOccupancy)} occupancy</p>}</div>}
 </aside>;
}
