import {useEffect,useState} from 'react';
import {BrainCircuit,ChevronRight,Shield,TriangleAlert,X} from 'lucide-react';
import type {Intelligence,Metrics} from '../types';

const sentenceCase=(value:string)=>value.toLowerCase().replace(/^./,letter=>letter.toUpperCase());
export function Understanding({intelligence,metrics,busy,status}:{intelligence?:Intelligence;metrics?:Metrics;busy:boolean;status:string}){
 const [details,setDetails]=useState<Intelligence|null>(null);
 useEffect(()=>{if(!details)return;const close=(event:KeyboardEvent)=>{if(event.key==='Escape')setDetails(null)};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close)},[details]);
 const findings=intelligence?.findings.filter(f=>!['traffic','quality'].includes(f.kind))||[];
 const state=intelligence?sentenceCase(intelligence.condition.replace(/ OBSERVED$/,'')):busy?'Connecting to the road':'Ready to observe';
 const trend=intelligence?.trend==='INSUFFICIENT HISTORY'?'Learning flow':intelligence?sentenceCase(intelligence.trend):'Waiting for playback';
 const recommendation=intelligence?.recommendation.startsWith('AVOID ROAD')?'Avoid road · blockage detected':intelligence?.recommendation.startsWith('USE ALTERNATE')?'Use alternate route · incident detected':intelligence?.recommendation.startsWith('POTENTIAL HAZARD')?'Potential hazard · review needed':intelligence?.recommendation.startsWith('CONSIDER')?'Consider an alternate route · verify':'Manual review before routing';
 return <><aside className="understanding surface calm-panel"><div className="section-title"><div><BrainCircuit size={18}/><h2>AEGIS AI</h2></div><span className={`panel-status ${status==='live'?'is-live':''}`}><i/>{status==='live'?'Live':status==='paused'?'Paused':status==='ended'?'Complete':['error','disconnected'].includes(status)?'Offline':busy?'Connecting':'Ready'}</span></div>
 <div className="calm-condition"><span className="small-label">VISIBLE ROAD CONDITION</span><h3>{state}</h3><span className="calm-trend">{trend}</span></div>
 <div className="compact-metrics live-metrics" aria-label="Current road measurements"><div><span>Vehicles</span><b>{metrics?.vehicleCount??'—'}</b></div><div><span>Moving</span><b>{metrics?metrics.vehicleCount-metrics.stoppedVehicles:'—'}</b></div><div><span>Stopped</span><b>{metrics?.stoppedVehicles??'—'}</b></div><div><span>Occupancy</span><b>{metrics?`${Math.round(metrics.roadOccupancy*100)}%`:'—'}</b></div></div>
 <div className="calm-alerts"><span className="small-label">RELEVANT FINDINGS</span><div className="calm-alert-list">{findings.length?findings.slice(0,3).map(finding=><div className="calm-alert" key={`${finding.kind}-${finding.title}`}><TriangleAlert size={15}/><div><b>{finding.title}</b><span title={finding.description}>{finding.description}</span></div></div>):<p className="calm-watching">{busy?'Watching for meaningful road changes.':'Important evidence appears here during playback.'}</p>}</div></div>
 <div className="calm-scores"><div><span>Road health</span><b>{intelligence?.roadHealthScore??'—'}<small>/100</small></b></div><div><span>Emergency access</span><b>{intelligence?.emergencyAccessScore??'—'}<small>/100</small></b></div></div>
 <div className="calm-recommendation"><Shield size={16}/><span>{intelligence?recommendation:'Press Play to begin'}</span></div><div className="calm-panel-footer"><span>Visual estimates · verify before routing</span><button onClick={()=>setDetails(intelligence||null)} disabled={!intelligence}>Details <ChevronRight size={13}/></button></div>
 </aside>
 {details&&<div className="evidence-modal" role="dialog" aria-modal="true" aria-label="Road assessment details" onClick={e=>{if(e.target===e.currentTarget)setDetails(null)}}><section className="surface assessment-details"><div className="section-title"><div><BrainCircuit size={18}/><h2>Road assessment details</h2></div><button autoFocus className="icon-button" aria-label="Close road details" onClick={()=>setDetails(null)}><X size={20}/></button></div><div className="evidence-modal-body"><p>{details.understanding}</p><h3>Supporting observations</h3>{details.findings.map(finding=><div className="assessment-observation" key={`${finding.kind}-${finding.title}`}><b>{finding.title}</b><p>{finding.description}</p>{finding.confidence!=null&&<small>{finding.confidenceType==='visual similarity'?'Visual match':'Detector score'} {finding.confidenceType==='visual similarity'?finding.confidence.toFixed(2):`${Math.round(finding.confidence*100)}%`}{finding.experimental?' · Experimental':''}</small>}</div>)}{details.trafficProjection&&<div className="assessment-observation"><b>60-second traffic-score projection: {Math.round(details.trafficProjection.projectedTrafficScore*100)}%</b><p>Linear trend extrapolation · experimental, not a probability.</p></div>}<h3>What supports this conclusion</h3><p>{details.cause==='UNRESOLVED'?'A specific cause has not been established.':details.cause}</p><ul>{details.sceneGraph.map((edge,index)=><li key={index}>{edge.from} {edge.relation} {edge.to}.</li>)}</ul><h3>Score deductions</h3><div className="penalties">{Object.entries(details.scorePenalties).filter(([,value])=>value>0).map(([key,value])=><div key={key}><span>{sentenceCase(key.replaceAll(/([A-Z])/g,' $1'))}</span><b>−{value.toFixed(1)}</b></div>)}</div><h3>Confidence & coverage</h3><p>{details.confidenceType}</p>{details.coverage.gaps.map(gap=><p key={gap}>{gap}</p>)}</div></section></div>}
 </>;
}
