/** Run against an isolated seeded integration backend; never a production city. */
const {chromium}=require('playwright');
const fs=require('fs');
const TARGET_URL=process.env.AEGIS_TEST_URL||'http://localhost:5180';
(async()=>{
 const browser=await chromium.launch({headless:process.env.AEGIS_TEST_HEADLESS==='true'});const errors=[];const result={};
 try{
  const contexts=await Promise.all(Array.from({length:4},()=>browser.newContext({viewport:{width:1440,height:1000},geolocation:{latitude:12.9716,longitude:77.5946},permissions:['geolocation']})));
  const [control,driver,hospital,citizen]=await Promise.all(contexts.map(c=>c.newPage()));for(const page of [control,driver,hospital,citizen])page.on('pageerror',e=>errors.push(e.message));
  async function city(){const r=await control.request.get(TARGET_URL+'/api/ecosystem/state');if(!r.ok())throw Error(await r.text());return (await r.json()).state}
  async function login(page,path,resource){await page.goto(TARGET_URL+path);await page.getByRole('button',{name:'Open workspace'}).waitFor();if(resource)await page.getByLabel(path==='/driver'?'Ambulance':'Hospital',{exact:true}).selectOption(resource);await page.getByRole('button',{name:'Open workspace'}).click();await page.locator('.platform-login').waitFor({state:'hidden'});}
  await login(control,'/legacy-operations');const before=await city();if(before.incidents.some(i=>!['COMPLETED','CANCELLED'].includes(i.status)))throw Error('Use an isolated database with no active emergency for this test');
  await control.getByRole('button',{name:'Seed demo network'}).click();await control.getByText('3',{exact:true}).first().waitFor();
  await citizen.goto(TARGET_URL+'/citizen');await citizen.getByLabel('Patient name').fill('Connected demo patient');await citizen.getByRole('button',{name:'Share this phone’s location'}).click();await citizen.getByLabel('I am with the patient',{exact:true}).check();await citizen.getByLabel('I confirm this is the incident location to share.',{exact:true}).check();await citizen.getByRole('button',{name:'Confirm pickup location',exact:true}).click();await citizen.getByRole('heading',{name:'Your emergency journey'}).waitFor();
  await control.getByRole('heading',{name:'Connected demo patient',exact:true}).first().waitFor();let state=await city();let incident=state.incidents.at(-1);result.incidentId=incident.id;result.ambulanceId=incident.ambulanceId;console.log('Citizen request dispatched:',incident.id);if(incident.ambulanceId!=='AMB-07')throw Error('Capability-based dispatch did not select the seeded ALS unit');
  await login(driver,'/driver',incident.ambulanceId);await driver.getByRole('button',{name:'Accept emergency',exact:true}).click();await driver.getByTestId('incident-status').filter({hasText:'EN ROUTE TO PATIENT'}).waitFor();await citizen.getByTestId('ambulance-label').filter({hasText:'AMB-07'}).waitFor();
  await driver.getByRole('button',{name:'Move ambulance · demo',exact:true}).click();await driver.getByRole('button',{name:'Arrived at patient',exact:true}).click();await driver.getByRole('button',{name:'Patient picked up',exact:true}).click();await driver.getByTestId('incident-status').filter({hasText:'HOSPITAL ASSIGNED'}).waitFor();
  state=await city();incident=state.incidents.find(e=>e.id===result.incidentId);result.hospitalId=incident.hospitalId;if(incident.hospitalId==='HOSP-A')throw Error('Nearest incapable hospital selected');
  await login(hospital,'/hospital',incident.hospitalId);await hospital.getByRole('button',{name:'Accept incoming patient',exact:true}).click();await driver.getByTestId('incident-status').filter({hasText:'EN ROUTE TO HOSPITAL'}).waitFor();
  state=await city();incident=state.incidents.find(e=>e.id===result.incidentId);const oldRoute=incident.routeId,oldEta=incident.etaSeconds,oldCorridor=state.corridors.find(c=>c.id===incident.corridorId).version;
  await control.getByRole('button',{name:'AI Camera',exact:true}).click();await control.getByRole('button',{name:'Register camera on active route',exact:true}).click();await control.getByLabel('Camera',{exact:true}).locator('option').filter({hasText:'Route camera'}).waitFor({state:'attached'});
  const videos=await (await control.request.get(TARGET_URL+'/api/videos')).json();if(!videos.some(v=>v.info.filename==='TEST - Accident aftermath (REAL).mp4')){const response=await control.request.post(TARGET_URL+'/api/videos/upload',{multipart:{file:{name:'TEST - Accident aftermath (REAL).mp4',mimeType:'video/mp4',buffer:fs.readFileSync(require('path').resolve(process.env.AEGIS_TEST_PROJECT||process.cwd(),'videos/samples/scenario-accident-aftermath.mp4'))}}});if(!response.ok())throw Error(await response.text());await control.reload();await control.getByRole('button',{name:'AI Camera',exact:true}).click();await control.getByLabel('Camera',{exact:true}).selectOption({label:'Route camera · Active demonstration route'});}
  await control.getByRole('button',{name:'Videos',exact:true}).click();await control.locator('.recent-dropdown button').filter({hasText:'TEST - Accident aftermath (REAL).mp4'}).click();let frames=[];control.on('websocket',ws=>ws.on('framereceived',frame=>{try{const value=JSON.parse(frame.payload);if(value.type==='frame')frames.push(value)}catch{}}));
  await control.getByRole('button',{name:'Play',exact:true}).click();await control.getByText('Accident aftermath detected',{exact:true}).first().waitFor({timeout:120000});while(!frames.length||frames.at(-1).videoTimestamp<8)await control.waitForTimeout(200);await control.getByRole('button',{name:'Pause',exact:true}).click();
  state=await city();incident=state.incidents.find(e=>e.id===result.incidentId);if(incident.routeId===oldRoute)throw Error('Real camera finding did not reroute the ambulance');if(incident.etaSeconds===oldEta)throw Error('Route ETA did not change');if(state.corridors.find(c=>c.id===incident.corridorId).version<=oldCorridor)throw Error('Corridor not recomputed');
  const cameraEvent=state.roadEvents.find(e=>e.source==='CAMERA'&&e.type==='ACCIDENT_AFTERMATH');if(!cameraEvent||!cameraEvent.evidenceImage)throw Error('Camera evidence was not persisted');await driver.getByTestId('eta').filter({hasText:Math.floor(incident.etaSeconds/60).toString().padStart(2,'0')}).waitFor();result.cameraEvent=cameraEvent.id;result.routeBefore=oldRoute;result.routeAfter=incident.routeId;result.etaBefore=oldEta;result.etaAfter=incident.etaSeconds;
  const citizenSnap=await (await citizen.request.get(TARGET_URL+'/api/v1/citizen/tracking')).json();const route=state.routes.find(r=>r.id===incident.routeId);if(JSON.stringify(citizenSnap.route.points)!==JSON.stringify(route.geometry))throw Error('Citizen route differs from driver route');result.sharedTrackingVerified=true;console.log('Actual camera evidence rerouted all views');
  await hospital.getByRole('button',{name:'Hospitals',exact:true}).click();await hospital.getByLabel('ICU beds',{exact:true}).fill('0');await hospital.getByRole('button',{name:'Save hospital capacity',exact:true}).click();await driver.getByTestId('incident-status').filter({hasText:'HOSPITAL ASSIGNED'}).waitFor();state=await city();incident=state.incidents.find(e=>e.id===result.incidentId);if(incident.hospitalId===result.hospitalId)throw Error('Capacity change did not divert the incident');result.alternativeHospital=incident.hospitalId;
  await hospital.request.delete(TARGET_URL+'/api/auth/session');await login(hospital,'/hospital',incident.hospitalId);await hospital.getByRole('button',{name:'Accept incoming patient',exact:true}).click();await driver.getByRole('button',{name:'Arrived at hospital',exact:true}).click();await hospital.getByRole('button',{name:'Confirm patient handover',exact:true}).click();await hospital.getByText('EMERGENCY COMPLETED',{exact:true}).waitFor();
  state=await city();incident=state.incidents.find(e=>e.id===result.incidentId);if(incident.status!=='COMPLETED')throw Error('Emergency did not complete');result.status=incident.status;result.timeline=incident.timeline.map(e=>e.type);result.browserErrors=errors;if(errors.length)throw Error(errors.join('; '));
  await citizen.reload();await citizen.getByTestId('status-title').filter({hasText:'This response is complete.'}).waitFor();result.refreshRecovery=true;
  const directory=process.env.AEGIS_TEST_ARTIFACTS||'/tmp/aegis-connected-flow';fs.mkdirSync(directory,{recursive:true});fs.writeFileSync(directory+'/results.json',JSON.stringify(result,null,2));
  for(const [name,page] of [['command',control],['driver',driver],['hospital',hospital],['citizen',citizen]])await page.screenshot({path:directory+'/'+name+'.png',fullPage:true,timeout:10000});
  console.log(JSON.stringify(result,null,2));
 }finally{await browser.close()}
})().catch(e=>{console.error(e);process.exitCode=1});
