package com.aegis.dispatch.service;

import com.aegis.dispatch.api.*;
import com.aegis.dispatch.api.ApiModels.*;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import java.time.*;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import static com.aegis.dispatch.api.ApiException.*;

@Service
public class DispatchService {
  private final JdbcTemplate jdbc; private final EventOutbox events; private final Duration staleAfter, maxPast, maxFuture, acknowledgementDeadline; private final Set<String> demoFailures=ConcurrentHashMap.newKeySet();
  public DispatchService(JdbcTemplate jdbc,EventOutbox events,@Value("${aegis.telemetry.stale-after-seconds}") long stale,@Value("${aegis.telemetry.max-past-seconds}") long past,@Value("${aegis.telemetry.max-future-seconds}") long future,@Value("${aegis.acknowledgement.deadline-seconds}") long acknowledgement){this.jdbc=jdbc;this.events=events;staleAfter=Duration.ofSeconds(stale);maxPast=Duration.ofSeconds(past);maxFuture=Duration.ofSeconds(future);acknowledgementDeadline=Duration.ofSeconds(acknowledgement);}

  public Map<String,Object> snapshot(String emergencyId){
    var mission=mission(emergencyId,false); var now=Instant.now(); var result=new LinkedHashMap<String,Object>();
    result.put("schemaVersion","v1");result.put("emergencyId",mission.s("emergency_id"));result.put("missionId",mission.uuid("id").toString());result.put("entityVersion",mission.l("version"));result.put("state",mission.s("status"));result.put("urgency",mission.s("urgency"));result.put("pickup",pickup(mission));result.put("requiredEquipment",tokens(mission.s("required_equipment")));result.put("requiredCrewCapabilities",tokens(mission.s("required_crew")));result.put("requiredCapacity",mission.i("required_capacity")>=2?"ADVANCED":"BASIC");result.put("notes",mission.s("operational_notes"));result.put("operator",Map.of("displayName",mission.s("confirming_operator"),"confirmedAt",mission.instant("confirmed_at").toString()));
    result.put("candidates",candidates(mission,now)); var assignment=activeAssignment(mission.uuid("id"),false); if(assignment!=null)result.put("assignment",assignment(assignment,mission));
    boolean routingDown=demoFailures.contains("ROUTING_OUTAGE"); result.put("providerHealth",Map.of("routing",routingDown?"UNAVAILABLE":"HEALTHY","realtime","CONNECTED","mode","SIMULATION"));result.put("alerts",alerts(assignment,now,routingDown));result.put("timeline",timeline(mission.uuid("id")));result.put("allowedActions",actions(mission,assignment));result.put("updatedAt",now.toString());return result;
  }

  @Transactional
  public Map<String,Object> dispatch(String emergencyId,DispatchRequest request,String actor,String role){
    var existing=jdbc.query("SELECT * FROM assignments WHERE idempotency_key=?",(rs,n)->row(rs),request.idempotencyKey()); if(!existing.isEmpty()) return snapshot(emergencyId);
    var mission=mission(emergencyId,true); if(mission.l("version")!=request.entityVersion())throw conflict("The mission changed while this ambulance was selected. Refresh candidates and try again.");
    if(!"READY_FOR_DISPATCH".equals(mission.s("status")))throw conflict("This mission is no longer ready for a new direct dispatch.");
    createAssignment(mission,request.ambulanceId(),request.idempotencyKey(),actor,role,"DIRECT_DISPATCH",null);return snapshot(emergencyId);
  }

  @Transactional
  public Map<String,Object> reassign(String emergencyId,ReassignRequest request,String actor,String role){
    var existing=jdbc.query("SELECT * FROM assignments WHERE idempotency_key=?",(rs,n)->row(rs),request.idempotencyKey());if(!existing.isEmpty())return snapshot(emergencyId);
    var mission=mission(emergencyId,true);if(mission.l("version")!=request.entityVersion())throw conflict("The mission changed while reassignment was being prepared.");var previous=activeAssignment(mission.uuid("id"),true);if(previous==null)throw conflict("No active assignment can be reassigned.");
    jdbc.update("UPDATE assignments SET status='SUPERSEDED',superseded_at=?,version=version+1 WHERE id=?",Instant.now(),previous.uuid("id"));jdbc.update("UPDATE ambulances SET status='AVAILABLE',version=version+1 WHERE id=? AND active_shift=true AND maintenance_restricted=false",previous.s("ambulance_id"));events.append("assignment",previous.uuid("id").toString(),"assignment.superseded",previous.l("version")+1,Map.of("reason",request.reason(),"missionId",mission.uuid("id").toString()));
    createAssignment(mission,request.ambulanceId(),request.idempotencyKey(),actor,role,"REASSIGNMENT",request.reason());return snapshot(emergencyId);
  }

  @Transactional
  public Map<String,Object> correctPickup(String emergencyId,PickupCorrectionRequest request,String actor,String role){
    var mission=mission(emergencyId,true);if(mission.l("version")!=request.entityVersion())throw conflict("The pickup changed before this correction could be saved.");var now=Instant.now();jdbc.update("INSERT INTO pickup_revisions(id,mission_id,mission_version_before,pickup,location_confirmation,location_source,accuracy_meters,address,landmark,access_instructions,justification,corrected_by,corrected_at) VALUES(?,?,?,ST_SetSRID(ST_MakePoint(?,?),4326)::geography,'CONFIRMED',?,?,?,?,?,?,?,?)",UUID.randomUUID(),mission.uuid("id"),mission.l("version"),request.longitude(),request.latitude(),request.source(),request.accuracyMeters(),request.address(),request.landmark(),request.accessInstructions(),request.justification(),actor,now);
    jdbc.update("UPDATE missions SET pickup=ST_SetSRID(ST_MakePoint(?,?),4326)::geography,location_confirmation='CONFIRMED',location_source=?,location_accuracy_meters=?,location_captured_at=?,address=?,landmark=?,access_instructions=?,confirming_operator=?,confirmed_at=?,version=version+1,updated_at=? WHERE id=?",request.longitude(),request.latitude(),request.source(),request.accuracyMeters(),now,request.address(),request.landmark(),request.accessInstructions(),actor,now,now,mission.uuid("id"));var changed=mission(emergencyId,false);var assignment=activeAssignment(changed.uuid("id"),true);if(assignment!=null)jdbc.update("UPDATE assignments SET pickup_change_acknowledged_at=NULL WHERE id=?",assignment.uuid("id"));events.audit(actor,role,"PICKUP_LOCATION_CORRECTED",changed.uuid("id"),assignment==null?null:assignment.uuid("id"),Map.of("justification",request.justification()));events.append("mission",changed.uuid("id").toString(),"pickup.location.changed",changed.l("version"),Map.of("missionId",changed.uuid("id").toString(),"routeVersion",changed.l("version")));return snapshot(emergencyId);
  }

  @Transactional
  public void telemetry(TelemetryUpload point,String actor){
    if(!point.ambulanceId().equals(ambulanceByDriver(actor,false).s("id")))throw forbidden("Drivers may only submit telemetry for their associated vehicle.");var amb=ambulance(point.ambulanceId(),true);var now=Instant.now();if(point.capturedAt().isBefore(now.minus(maxPast))||point.capturedAt().isAfter(now.plus(maxFuture)))throw invalid("Telemetry capture time is outside the accepted clock-skew window.");
    boolean active=jdbc.queryForObject("SELECT EXISTS(SELECT 1 FROM assignments WHERE ambulance_id=? AND status='ACTIVE')",Boolean.class,amb.s("id"));if(!amb.b("active_shift")&&!active)throw forbidden("Telemetry is not authorized while off duty without an active mission.");String currentSession=amb.s("latest_tracking_session_id");if(currentSession!=null&&currentSession.equals(point.trackingSessionId())&&point.sequenceNumber()<=amb.l("latest_sequence"))throw conflict("Duplicate or out-of-order telemetry point.");if(amb.instantOrNull("latest_captured_at")!=null&&point.capturedAt().isBefore(amb.instantOrNull("latest_captured_at")))throw conflict("Buffered historical telemetry cannot replace a newer position.");
    boolean jump=false;if(amb.dOrNull("latitude")!=null){double distance=Geo.meters(amb.d("latitude"),amb.d("longitude"),point.latitude(),point.longitude());long seconds=Math.max(1,Duration.between(amb.instantOrNull("latest_captured_at"),point.capturedAt()).abs().toSeconds());jump=distance/seconds>55;}
    jdbc.update("INSERT INTO telemetry_points(ambulance_id,tracking_session_id,sequence_number,captured_at,position,accuracy_meters,bearing_degrees,speed_mps,flagged) VALUES(?,?,?, ?,ST_SetSRID(ST_MakePoint(?,?),4326)::geography,?,?,?,?)",point.ambulanceId(),UUID.fromString(point.trackingSessionId()),point.sequenceNumber(),point.capturedAt(),point.longitude(),point.latitude(),point.accuracyMeters(),point.bearingDegrees(),point.speedMps(),jump);
    jdbc.update("UPDATE ambulances SET latest_position=ST_SetSRID(ST_MakePoint(?,?),4326)::geography,latest_accuracy_meters=?,latest_bearing_degrees=?,latest_speed_mps=?,latest_captured_at=?,latest_tracking_session_id=?,latest_sequence=?,telemetry_flagged=?,version=version+1 WHERE id=?",point.longitude(),point.latitude(),point.accuracyMeters(),point.bearingDegrees(),point.speedMps(),point.capturedAt(),UUID.fromString(point.trackingSessionId()),point.sequenceNumber(),jump,point.ambulanceId());var updated=ambulance(point.ambulanceId(),false);events.append("ambulance",updated.s("id"),"ambulance.location.updated",updated.l("version"),Map.of("ambulanceId",updated.s("id"),"flagged",jump,"capturedAt",point.capturedAt().toString()));
  }

  @Transactional public void receipt(UUID assignmentId,String actor){var a=assignment(assignmentId,true);authorizeDriver(a,actor);jdbc.update("UPDATE assignments SET received_at=COALESCE(received_at,?),version=version+1 WHERE id=?",Instant.now(),assignmentId);events.append("assignment",assignmentId.toString(),"assignment.received",a.l("version")+1,Map.of("assignmentId",assignmentId.toString()));}
  @Transactional public void acknowledge(UUID assignmentId,String actor){var a=assignment(assignmentId,true);authorizeDriver(a,actor);if(!"ACTIVE".equals(a.s("status")))throw conflict("This assignment has been superseded.");var now=Instant.now();jdbc.update("UPDATE assignments SET acknowledged_at=COALESCE(acknowledged_at,?),en_route_at=COALESCE(en_route_at,?),version=version+1 WHERE id=?",now,now,assignmentId);jdbc.update("UPDATE missions SET status='EN_ROUTE_TO_PATIENT',version=version+1,updated_at=? WHERE id=?",now,a.uuid("mission_id"));events.append("assignment",assignmentId.toString(),"assignment.acknowledged",a.l("version")+1,Map.of("assignmentId",assignmentId.toString()));}
  @Transactional public void arrive(UUID assignmentId,String actor){var a=assignment(assignmentId,true);authorizeDriver(a,actor);if(!"ACTIVE".equals(a.s("status")))throw conflict("This assignment is no longer active.");if(a.instantOrNull("acknowledged_at")==null)throw conflict("Acknowledge the confirmed assignment before marking arrival.");var now=Instant.now();jdbc.update("UPDATE assignments SET arrived_at=COALESCE(arrived_at,?),version=version+1 WHERE id=?",now,assignmentId);jdbc.update("UPDATE missions SET status='AT_PATIENT',version=version+1,updated_at=? WHERE id=?",now,a.uuid("mission_id"));events.append("assignment",assignmentId.toString(),"mission.state.changed",a.l("version")+1,Map.of("state","AT_PATIENT","assignmentId",assignmentId.toString()));}
  public Map<String,Object> driverSnapshot(String actor){var amb=ambulanceByDriver(actor,false);var active=jdbc.query("SELECT * FROM assignments WHERE driver_id=? AND status='ACTIVE'",(rs,n)->row(rs),actor);var result=new LinkedHashMap<String,Object>();result.put("ambulance",ambulanceDto(amb));result.put("assignment",active.isEmpty()?null:assignment(active.getFirst(),mission(active.getFirst().s("mission_id"),false)));result.put("serverTime",Instant.now().toString());return result;}
  @Transactional public void pickupChangeAcknowledged(UUID assignmentId,String actor){var a=assignment(assignmentId,true);authorizeDriver(a,actor);jdbc.update("UPDATE assignments SET pickup_change_acknowledged_at=?,version=version+1 WHERE id=?",Instant.now(),assignmentId);events.append("assignment",assignmentId.toString(),"pickup.change.acknowledged",a.l("version")+1,Map.of("assignmentId",assignmentId.toString()));}
  @Transactional public void operationalProblem(UUID assignmentId,String category,String detail,String actor){var a=assignment(assignmentId,true);authorizeDriver(a,actor);if(!"ACTIVE".equals(a.s("status")))throw conflict("A problem cannot be added to a superseded assignment.");var id=UUID.randomUUID();jdbc.update("INSERT INTO operational_problems(id,assignment_id,category,detail,reported_by,reported_at) VALUES(?,?,?,?,?,?)",id,assignmentId,category,detail,actor,Instant.now());events.audit(actor,"DRIVER","OPERATIONAL_PROBLEM_REPORTED",a.uuid("mission_id"),assignmentId,Map.of("category",category,"detail",detail));events.append("assignment",assignmentId.toString(),"operational.problem.reported",a.l("version"),Map.of("assignmentId",assignmentId.toString(),"category",category));}
  @Transactional public void registerPushToken(String token,String platform,String actor){jdbc.update("INSERT INTO driver_push_tokens(token,driver_id,platform,created_at,last_seen_at) VALUES(?,?,?,?,?) ON CONFLICT (token) DO UPDATE SET driver_id=EXCLUDED.driver_id,platform=EXCLUDED.platform,last_seen_at=EXCLUDED.last_seen_at",token,actor,platform,Instant.now(),Instant.now());}
  @Transactional public void removePushToken(String token,String actor){jdbc.update("DELETE FROM driver_push_tokens WHERE token=? AND driver_id=?",token,actor);}
  @Transactional public void resetDemo(String actor,String role){jdbc.update("DELETE FROM operational_problems");jdbc.update("DELETE FROM assignments");jdbc.update("DELETE FROM telemetry_points");jdbc.update("DELETE FROM pickup_revisions");jdbc.update("DELETE FROM event_outbox");jdbc.update("DELETE FROM audit_log");jdbc.update("UPDATE missions SET status='READY_FOR_DISPATCH',version=0,pickup=ST_SetSRID(ST_MakePoint(77.5946,12.9716),4326)::geography,location_confirmation='CONFIRMED',location_source='OPERATOR_CONFIRMED',location_accuracy_meters=18,address='42 Residency Road, Bengaluru',landmark='North gate, opposite Metro entrance',access_instructions='Use north gate; patient is on ground floor.',updated_at=now()");jdbc.update("UPDATE ambulances SET status=CASE id WHEN 'AMB-C' THEN 'BUSY' WHEN 'AMB-D' THEN 'OFF_DUTY' ELSE 'AVAILABLE' END, latest_captured_at=CASE WHEN id='AMB-E' THEN now()-interval '5 minutes' ELSE now() END,version=0,telemetry_flagged=false");demoFailures.clear();events.audit(actor,role,"DEMO_RESET",UUID.fromString("00000000-0000-0000-0000-000000000101"),null,Map.of("simulation",true));}
  public void failure(String mode){demoFailures.clear();if(!"NONE".equals(mode))demoFailures.add(mode);}

  private void createAssignment(Row mission,String ambulanceId,String idempotency,String actor,String role,String action,String reason){var ambulance=ambulance(ambulanceId,true);var exclusions=Eligibility.exclusions(vehicle(ambulance),requirements(mission),Instant.now(),staleAfter);if(!exclusions.isEmpty())throw conflict("Ambulance cannot be dispatched: "+String.join("; ",exclusions));var now=Instant.now();UUID id=UUID.randomUUID();try{jdbc.update("INSERT INTO assignments(id,mission_id,ambulance_id,driver_id,status,idempotency_key,assigned_at,acknowledgement_deadline_at) VALUES(?,?,?,?,'ACTIVE',?,?,?)",id,mission.uuid("id"),ambulance.s("id"),ambulance.s("driver_id"),idempotency,now,now.plus(acknowledgementDeadline));}catch(Exception e){throw conflict("Ambulance availability changed during dispatch. Refresh candidates.");}jdbc.update("UPDATE ambulances SET status='ASSIGNED',version=version+1,updated_at=? WHERE id=?",now,ambulance.s("id"));jdbc.update("UPDATE missions SET status='ASSIGNED',version=version+1,updated_at=? WHERE id=?",now,mission.uuid("id"));var updated=mission(mission.s("emergency_id"),false);events.audit(actor,role,action,updated.uuid("id"),id,reason==null?Map.of("ambulanceId",ambulanceId):Map.of("ambulanceId",ambulanceId,"reason",reason));events.append("assignment",id.toString(),"assignment.confirmed",updated.l("version"),Map.of("assignmentId",id.toString(),"missionId",updated.uuid("id").toString(),"ambulanceId",ambulanceId));}
  private List<Map<String,Object>> candidates(Row mission,Instant now){var rows=jdbc.query("SELECT a.*,ST_Y(a.latest_position::geometry) latitude,ST_X(a.latest_position::geometry) longitude FROM ambulances a ORDER BY a.id",(rs,n)->row(rs));var list=new ArrayList<Map<String,Object>>();int rank=0;for(var a:rows){var exclusions=Eligibility.exclusions(vehicle(a),requirements(mission),now,staleAfter);var item=new LinkedHashMap<String,Object>();item.put("ambulance",ambulanceDto(a));item.put("eligible",exclusions.isEmpty());if(exclusions.isEmpty()){double distance=Geo.meters(a.d("latitude"),a.d("longitude"),mission.d("latitude"),mission.d("longitude"));if(demoFailures.contains("ROUTING_OUTAGE")){item.put("etaSource","UNAVAILABLE");item.put("reasons",List.of("Eligible, but traffic-aware routing is unavailable. Authorized operator judgement is required."));}else{int eta=(int)Math.max(90,Math.round(distance/9.5));item.put("ranking",++rank);item.put("roadEtaSeconds",eta);item.put("roadDistanceMeters",Math.round(distance*1.18));item.put("etaSource","APPROXIMATE");item.put("etaCalculatedAt",now.toString());item.put("reasons",List.of("Meets confirmed equipment, crew, capacity, readiness, and freshness requirements","Ranked by deterministic demonstration road estimate"));}}else{item.put("etaSource","UNAVAILABLE");item.put("exclusionReasons",exclusions);}list.add(item);}return list;}
  private Map<String,Object> ambulanceDto(Row a){var x=new LinkedHashMap<String,Object>();x.put("ambulanceId",a.s("id"));x.put("callSign",a.s("id"));x.put("status",status(a));x.put("readiness",a.b("vehicle_ready")&&a.b("equipment_ready")&&a.b("crew_ready")?"READY":"UNAVAILABLE");x.put("capabilities",tokens(a.s("equipment_capabilities")));x.put("crewCapabilities",tokens(a.s("crew_capabilities")));x.put("capacity",a.i("capacity")>=2?"ADVANCED":"BASIC");if(a.dOrNull("latitude")!=null){var t=new LinkedHashMap<String,Object>();t.put("trackingSessionId",a.s("latest_tracking_session_id"));t.put("sequenceNumber",a.l("latest_sequence"));t.put("capturedAt",a.instantOrNull("latest_captured_at").toString());t.put("coordinates",Map.of("latitude",a.d("latitude"),"longitude",a.d("longitude")));t.put("accuracyMeters",a.obj("latest_accuracy_meters"));t.put("bearingDegrees",a.obj("latest_bearing_degrees"));t.put("speedKph",a.obj("latest_speed_mps")==null?null:Math.round(a.d("latest_speed_mps")*3.6));t.put("freshness",a.instantOrNull("latest_captured_at").isBefore(Instant.now().minus(staleAfter))?"STALE":"LIVE");x.put("telemetry",t);}return x;}
  private Map<String,Object> assignment(Row a,Row m){var r=new LinkedHashMap<String,Object>();r.put("assignmentId",a.uuid("id").toString());r.put("emergencyId",m.s("emergency_id"));r.put("missionId",m.uuid("id").toString());r.put("ambulanceId",a.s("ambulance_id"));r.put("entityVersion",m.l("version"));r.put("state",a.s("status").equals("ACTIVE")?"CONFIRMED":a.s("status"));r.put("confirmedAt",a.instant("assigned_at").toString());r.put("pickup",pickup(m));r.put("requiredEquipment",tokens(m.s("required_equipment")));r.put("requiredCrewCapabilities",tokens(m.s("required_crew")));r.put("operationalNotes",m.s("operational_notes"));r.put("permittedActions",List.of("RECEIPT","ACKNOWLEDGEMENT","PICKUP_CHANGE_ACKNOWLEDGEMENT","ARRIVAL","OPERATIONAL_PROBLEM"));putInstant(r,"receivedAt",a.instantOrNull("received_at"));putInstant(r,"acknowledgedAt",a.instantOrNull("acknowledged_at"));putInstant(r,"enRouteAt",a.instantOrNull("en_route_at"));putInstant(r,"acknowledgementDeadline",a.instantOrNull("acknowledgement_deadline_at"));putInstant(r,"pickupChangeAcknowledgedAt",a.instantOrNull("pickup_change_acknowledged_at"));var amb=ambulance(a.s("ambulance_id"),false);if(!demoFailures.contains("ROUTING_OUTAGE"))r.put("route",Map.of("routeVersion",m.l("version"),"status","AVAILABLE","provider","DEMO_ADAPTER","calculatedAt",Instant.now().toString(),"distanceMeters",Math.round(Geo.meters(amb.d("latitude"),amb.d("longitude"),m.d("latitude"),m.d("longitude"))*1.18),"durationSeconds",Math.max(90,(int)(Geo.meters(amb.d("latitude"),amb.d("longitude"),m.d("latitude"),m.d("longitude"))/9.5)),"geometry",List.of(Map.of("latitude",amb.d("latitude"),"longitude",amb.d("longitude")),Map.of("latitude",m.d("latitude"),"longitude",m.d("longitude")))));return r;}
  private List<Map<String,Object>> alerts(Row assignment,Instant now,boolean routingDown){var r=new ArrayList<Map<String,Object>>();if(routingDown)r.add(alert("WARNING","Routing unavailable","Traffic-aware ETA and route geometry are unavailable; use authorized operator judgement."));if(assignment!=null&&assignment.instantOrNull("acknowledged_at")==null&&(assignment.instant("acknowledgement_deadline_at").isBefore(now)||demoFailures.contains("ACKNOWLEDGEMENT_TIMEOUT")))r.add(alert("CRITICAL","Driver acknowledgement overdue","Start the configured contact/escalation procedure; do not assume a push was seen."));if(demoFailures.contains("DRIVER_OFFLINE"))r.add(alert("CRITICAL","Driver app offline","Assignment may be confirmed but receipt is not evidence of human acknowledgement."));if(demoFailures.contains("GPS_DISABLED"))r.add(alert("WARNING","GPS disabled","The driver device must restore GPS before current location is reliable."));if(demoFailures.contains("STALE_TELEMETRY"))r.add(alert("WARNING","Telemetry stale","Last-known positions must not be animated as live movement."));if(demoFailures.contains("EQUIPMENT_FAILURE"))r.add(alert("CRITICAL","Equipment readiness exception","Operator review or safe reassignment is required."));return r;}
  private Map<String,Object> alert(String level,String label,String detail){return Map.of("alertId",UUID.randomUUID().toString(),"level",level,"label",label,"detail",detail,"occurredAt",Instant.now().toString());}
  private List<Map<String,Object>> timeline(UUID missionId){return jdbc.query("SELECT event_type,occurred_at,entity_version,id FROM event_outbox WHERE aggregate_id=? OR aggregate_id IN (SELECT id::text FROM assignments WHERE mission_id=?) ORDER BY occurred_at DESC LIMIT 20",(rs,n)->Map.of("eventId",rs.getObject("id").toString(),"occurredAt",rs.getTimestamp("occurred_at").toInstant().toString(),"label",rs.getString("event_type"),"detail","Durable operational event","kind","SYSTEM"),missionId.toString(),missionId);}
  private List<String> actions(Row mission,Row assignment){var x=new ArrayList<String>();if("READY_FOR_DISPATCH".equals(mission.s("status")))x.add("DISPATCH_AMBULANCE");x.add("CORRECT_PICKUP");if(assignment!=null)x.add("REASSIGN_AMBULANCE");x.add("RESET_DEMO");x.add("INJECT_FAILURE");return x;}
  private Map<String,Object> pickup(Row m){var p=new LinkedHashMap<String,Object>();p.put("coordinates",Map.of("latitude",m.d("latitude"),"longitude",m.d("longitude")));p.put("source",m.s("location_source"));p.put("confirmationStatus",m.s("location_confirmation"));p.put("accuracyMeters",m.obj("location_accuracy_meters"));p.put("capturedAt",m.instant("location_captured_at").toString());p.put("confirmedAt",m.instant("confirmed_at").toString());p.put("address",m.s("address"));p.put("landmark",m.s("landmark"));p.put("accessInstructions",m.s("access_instructions"));return p;}
  private void putInstant(Map<String,Object> out,String key,Instant v){if(v!=null)out.put(key,v.toString());}
  private Eligibility.Vehicle vehicle(Row a){return new Eligibility.Vehicle(a.s("status"),a.b("active_shift"),a.b("vehicle_ready"),a.b("equipment_ready"),a.b("crew_ready"),a.b("maintenance_restricted"),a.i("capacity"),new HashSet<>(tokens(a.s("equipment_capabilities"))),new HashSet<>(tokens(a.s("crew_capabilities"))),a.instantOrNull("latest_captured_at"));}
  private Eligibility.Requirement requirements(Row m){return new Eligibility.Requirement(new HashSet<>(tokens(m.s("required_equipment"))),new HashSet<>(tokens(m.s("required_crew"))),m.i("required_capacity"));}
  private List<String> tokens(String value){return value==null||value.isBlank()?List.of():Arrays.stream(value.split(",")).map(String::trim).filter(s->!s.isBlank()).toList();}
  private String status(Row a){return a.instantOrNull("latest_captured_at")!=null&&a.instantOrNull("latest_captured_at").isBefore(Instant.now().minus(staleAfter))?"STALE":a.s("status");}
  private Row mission(String key,boolean lock){var byUuid=key.matches("[0-9a-fA-F-]{36}");var rows=jdbc.query("SELECT m.*,ST_Y(m.pickup::geometry) latitude,ST_X(m.pickup::geometry) longitude FROM missions m WHERE "+(byUuid?"m.id=?":"m.emergency_id=?")+(lock?" FOR UPDATE":""),(rs,n)->row(rs),byUuid?UUID.fromString(key):key);if(rows.isEmpty())throw notFound("Mission was not found.");return rows.getFirst();}
  private Row ambulance(String id,boolean lock){var rows=jdbc.query("SELECT a.*,ST_Y(a.latest_position::geometry) latitude,ST_X(a.latest_position::geometry) longitude FROM ambulances a WHERE a.id=?"+(lock?" FOR UPDATE":""),(rs,n)->row(rs),id);if(rows.isEmpty())throw notFound("Ambulance was not found.");return rows.getFirst();}
  private Row ambulanceByDriver(String driver,boolean lock){var rows=jdbc.query("SELECT a.*,ST_Y(a.latest_position::geometry) latitude,ST_X(a.latest_position::geometry) longitude FROM ambulances a WHERE a.driver_id=?"+(lock?" FOR UPDATE":""),(rs,n)->row(rs),driver);if(rows.isEmpty())throw forbidden("No vehicle association is active for this driver.");return rows.getFirst();}
  private Row activeAssignment(UUID missionId,boolean lock){var rows=jdbc.query("SELECT * FROM assignments WHERE mission_id=? AND status='ACTIVE'"+(lock?" FOR UPDATE":""),(rs,n)->row(rs),missionId);return rows.isEmpty()?null:rows.getFirst();}
  private Row assignment(UUID id,boolean lock){var rows=jdbc.query("SELECT * FROM assignments WHERE id=?"+(lock?" FOR UPDATE":""),(rs,n)->row(rs),id);if(rows.isEmpty())throw notFound("Assignment was not found.");return rows.getFirst();}
  private void authorizeDriver(Row assignment,String actor){if(!actor.equals(assignment.s("driver_id")))throw forbidden("Drivers may only access their current assignment.");}
  private static Row row(java.sql.ResultSet rs){try{var data=new HashMap<String,Object>();var md=rs.getMetaData();for(int i=1;i<=md.getColumnCount();i++)data.put(md.getColumnLabel(i),rs.getObject(i));return new Row(data);}catch(Exception e){throw new IllegalStateException(e);}}
  private record Row(Map<String,Object> d){Object obj(String k){return d.get(k);}String s(String k){var x=d.get(k);return x==null?null:x.toString();}long l(String k){return ((Number)d.get(k)).longValue();}int i(String k){return ((Number)d.get(k)).intValue();}boolean b(String k){return (Boolean)d.get(k);}double d(String k){return ((Number)d.get(k)).doubleValue();}Double dOrNull(String k){var x=d.get(k);return x==null?null:((Number)x).doubleValue();}UUID uuid(String k){var x=d.get(k);return x instanceof UUID u?u:UUID.fromString(x.toString());}Instant instant(String k){return ((java.sql.Timestamp)d.get(k)).toInstant();}Instant instantOrNull(String k){return d.get(k)==null?null:instant(k);}}
}
