import React,{useEffect,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Activity,Camera,ChevronDown,Download,FileVideo,History,LoaderCircle,Pause,Play,Settings2,Shield,Square,Upload,X} from 'lucide-react';
import {api,timestamp} from './services/api';
import {Understanding} from './components/Understanding';
import {LiveCanvas} from './components/LiveCanvas';
import {RoadTimeline} from './components/RoadTimeline';
import type {Video as RoadVideo,LivePacket,LiveEvent} from './types';
import './style.css';
function evidenceLines(details:Record<string,unknown>):string[]{
 const evidence=details.evidence;
 if(Array.isArray(evidence))return evidence.filter((v):v is string=>typeof v==='string');
 if(evidence&&typeof evidence==='object'){
  const data=evidence as Record<string,unknown>;
  if(typeof data.count==='number')return [`${data.count} persistent object observations`];
  const counts=Object.entries(data).flatMap(([kind,value])=>value&&typeof value==='object'&&'count' in value?[`${(value as {count:number}).count} ${kind.replaceAll('_',' ')}`]:[]);
  if(counts.length)return counts;
 }
 return Object.entries(details).flatMap(([key,value])=>{
  if(key==='experimental'||key==='confidenceType'||key==='trackIds'||key==='trackId')return [];
  if(typeof value==='number')return [`${key.replaceAll(/([A-Z])/g,' $1')}: ${value.toFixed(value%1?2:0)}`];
  if(typeof value==='string')return [value];return [];
 });
}
function App(){
 const [video,setVideo]=useState<RoadVideo|null>(null),[videos,setVideos]=useState<RoadVideo[]>([]),[camera,setCamera]=useState(false),[configured,setConfigured]=useState(false),[cameraSource,setCameraSource]=useState('browser'),[status,setStatus]=useState('ready'),[packet,setPacket]=useState<LivePacket|null>(null),[frame,setFrame]=useState<LivePacket|null>(null),[events,setEvents]=useState<LiveEvent[]>([]),[session,setSession]=useState<string|null>(null),[error,setError]=useState(''),[uploading,setUploading]=useState(false),[settings,setSettings]=useState(false),[recent,setRecent]=useState(false),[mode,setMode]=useState('SMART'),[view,setView]=useState(true),[developer,setDeveloper]=useState(false),[filter,setFilter]=useState('IMPORTANT'),[seekValue,setSeekValue]=useState<number|null>(null),[selected,setSelected]=useState<LiveEvent|null>(null),[drag,setDrag]=useState(false);
 const file=useRef<HTMLInputElement>(null),socket=useRef<WebSocket|null>(null),sessionRef=useRef<string|null>(null),generation=useRef(0),wantPlay=useRef(false),media=useRef<MediaStream|null>(null),cameraVideo=useRef<HTMLVideoElement|null>(null),cameraTimer=useRef<ReturnType<typeof setInterval>|null>(null),statusRef=useRef('ready'),sent=useRef(false),connectPromise=useRef<Promise<void>|null>(null),displayTimes=useRef<number[]>([]),[displayFPS,setDisplayFPS]=useState(0);
 const busy=['live','initializing','connecting'].includes(status),intelligence=packet?.intelligence;
 useEffect(()=>{api<RoadVideo[]>('/api/videos').then(setVideos).catch(e=>setError(e.message));api<{configuredCamera:boolean}>('/api/live/sources').then(x=>setConfigured(x.configuredCamera)).catch(()=>{});return()=>cleanup()},[]);
 useEffect(()=>{statusRef.current=status},[status]);
 function cleanup(){wantPlay.current=false;socket.current?.close();socket.current=null;sessionRef.current=null;connectPromise.current=null;if(cameraTimer.current)clearInterval(cameraTimer.current);cameraTimer.current=null;media.current?.getTracks().forEach(t=>t.stop());media.current=null;cameraVideo.current=null;}
 function reset(){cleanup();generation.current=0;setSession(null);setPacket(null);setFrame(null);setEvents([]);setStatus('ready');setError('');setSelected(null);sent.current=false;}
 function select(item:RoadVideo){reset();setVideo(item);setCamera(false);setRecent(false)}
 async function upload(source:File){reset();setUploading(true);const form=new FormData();form.append('file',source);try{const item=await api<RoadVideo>('/api/videos/upload',{method:'POST',body:form});setVideo(item);setCamera(false);setVideos(await api('/api/videos'))}catch(e){setError((e as Error).message)}finally{setUploading(false)}}
 async function chooseCamera(source='browser'){reset();setVideo(null);setCamera(true);setCameraSource(source);if(source==='configured')return;try{const stream=await navigator.mediaDevices.getUserMedia({video:{width:{ideal:960},height:{ideal:540}},audio:false});media.current=stream;const el=document.createElement('video');el.muted=true;el.srcObject=stream;await el.play();cameraVideo.current=el;}catch(e){setError((e as Error).message);setCamera(false)}}
 function send(command:string,stamp?:number){socket.current?.readyState===WebSocket.OPEN&&socket.current.send(JSON.stringify({command,timestamp:stamp}))}
 async function connect(){
  if(socket.current?.readyState===WebSocket.OPEN)return;if(connectPromise.current)return connectPromise.current;
  connectPromise.current=(async()=>{setStatus('connecting');const result=await api<{sessionId:string}>('/api/live/sessions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({videoId:video?.id||null,mode,source:video?'browser':cameraSource})});setSession(result.sessionId);sessionRef.current=result.sessionId;
   const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/vision/${result.sessionId}`);socket.current=ws;
   ws.onmessage=event=>{const data=JSON.parse(event.data);if(ws!==socket.current)return;
    if(data.type==='status'){generation.current=data.generation;setStatus(data.status);if(data.error)setError(data.error);if(['stopped','paused'].includes(data.status)&&data.timestamp===0)setPacket(null)}
    else if(data.type==='frame'){if(data.generation!==generation.current){send('ack');return}setFrame(data);sent.current=false;}
    else if(data.type==='error')setError(data.message);
   };ws.onclose=()=>{if(ws===socket.current){setStatus('disconnected');connectPromise.current=null}};ws.onerror=()=>setError('The live stream connection failed.');
   await new Promise<void>((resolve,reject)=>{ws.onopen=()=>resolve();ws.addEventListener('error',()=>reject(new Error('Could not connect to live vision')),{once:true})});
   if(camera&&cameraSource==='browser'){const canvas=document.createElement('canvas');cameraTimer.current=setInterval(()=>{const el=cameraVideo.current;if(!el||statusRef.current!=='live'||sent.current||ws.readyState!==WebSocket.OPEN||ws.bufferedAmount>200000)return;canvas.width=Math.min(960,el.videoWidth);canvas.height=Math.round(el.videoHeight*canvas.width/el.videoWidth);canvas.getContext('2d')?.drawImage(el,0,0,canvas.width,canvas.height);sent.current=true;canvas.toBlob(blob=>{if(blob&&ws.readyState===WebSocket.OPEN)ws.send(blob);else sent.current=false},'image/jpeg',.78)},67)}
  })();try{await connectPromise.current}catch(e){connectPromise.current=null;setStatus('error');throw e}
 }
 async function play(){try{wantPlay.current=true;await connect();if(wantPlay.current)send('play')}catch(e){setError((e as Error).message)}}
 function pause(){wantPlay.current=false;generation.current+=1;send('pause');setStatus('paused');sent.current=false}
 function stop(){wantPlay.current=false;generation.current+=1;send('stop');setStatus('stopped');setPacket(null);setFrame(null);sent.current=false}
 function seek(time:number){if(!socket.current)return;generation.current+=1;setPacket(null);setFrame(null);setSelected(null);send('seek',time);setSeekValue(null)}
 function rendered(next:LivePacket|null){if(next&&next.generation===generation.current){setPacket(next);setEvents(previous=>{const signature=(items:LiveEvent[])=>items.map(e=>`${e.eventId}:${e.state}:${e.story.length}:${e.story.at(-1)?.time??''}:${e.evidence.event?.image||''}`).join('|');return signature(previous)===signature(next.events)?previous:next.events})}send('ack');const now=performance.now();displayTimes.current=displayTimes.current.filter(x=>now-x<1000);displayTimes.current.push(now);setDisplayFPS(displayTimes.current.length)}
 const shown=events.filter(e=>filter==='ALL'||(filter==='CRITICAL'?e.severity==='CRITICAL':e.severity!=='INFO'));
 const label=status==='live'?'AI LIVE':status==='initializing'||status==='connecting'?'INITIALIZING AI':status==='paused'?'AI PAUSED':status==='ended'?'PLAYBACK COMPLETE':status==='error'||status==='disconnected'?'AI DISCONNECTED':'AI READY';
 const time=seekValue??packet?.videoTimestamp??0;const selectedEvent=events.find(e=>e.eventId===selected?.eventId)||selected;
 return <div className="omnivision"><header className="topbar"><a className="brand" href="/" aria-label="AEGIS OmniVision home"><span className="brand-symbol"><Shield size={25}/></span><div>AEGIS <b>OMNIVISION</b><small>LIVE VISION ENGINE</small></div></a><div className="top-actions"><span className={`engine-state ${status==='live'?'online':''}`}><i/>{label}</span><button className="settings-button" onClick={()=>setSettings(!settings)}><Settings2 size={17}/><span>Settings</span></button></div></header>
 <main><section className="intro"><div><div className="eyebrow">WATCH. UNDERSTAND. RECORD. EXPLAIN.</div><h1>{intelligence?'The road, understood live.':'Press play. The road comes into focus.'}</h1><p>Live frames, connected evidence and one evolving road story.</p></div><div className="intro-actions">{videos.length>0&&<div className="recent-wrapper"><button className="secondary" onClick={()=>setRecent(!recent)}><History size={16}/> Videos <ChevronDown size={14}/></button>{recent&&<div className="recent-dropdown">{videos.map(item=><button key={item.id} onClick={()=>select(item)}><FileVideo size={16}/><div><b>{item.info.filename}</b><small>{timestamp(item.info.durationSeconds)} · Play with live AI</small></div></button>)}</div>}</div>}<button className="secondary" onClick={()=>void chooseCamera()}><Camera size={16}/> Camera</button><button className="primary" disabled={uploading} onClick={()=>file.current?.click()}>{uploading?<LoaderCircle size={16} className="spin"/>:<Upload size={16}/>} {uploading?'Uploading…':'Upload video'}</button></div></section>
 <input ref={file} hidden type="file" accept=".mp4,.mov,.avi,.mkv" onChange={e=>{const chosen=e.target.files?.[0];if(chosen)void upload(chosen);e.target.value=''}}/>
 {settings&&<section className="settings-panel surface"><div className="settings-heading"><Settings2 size={17}/><h2>Live vision settings</h2><button className="icon-button" aria-label="Close settings" onClick={()=>setSettings(false)}><X size={17}/></button></div><div className="settings-grid"><div><label htmlFor="live-mode">Detection scheduling</label><select id="live-mode" disabled={!!session} value={mode} onChange={e=>setMode(e.target.value)}><option value="FAST">FAST · correction every 3 processed frames</option><option value="SMART">SMART · correction every 2 processed frames</option><option value="MAX">MAX · correction every processed frame</option></select><p>Motion tracking continues between detections. Old frames are discarded when inference is busy. Select a source again to change modes.</p></div><div>{configured&&<button className="secondary" onClick={()=>{void chooseCamera('configured');setSettings(false)}}><Camera size={16}/> Connect configured CCTV</button>}<label className="developer-toggle"><input type="checkbox" checked={developer} onChange={e=>setDeveloper(e.target.checked)}/> Developer performance monitor</label><p>Road segmentation and object evidence refresh at separate intervals. Anomalies increase detection frequency.</p></div></div></section>}
 {error&&<div className="error" role="alert"><Activity size={18}/><span>{error}</span><button className="icon-button" aria-label="Dismiss error" onClick={()=>setError('')}><X size={16}/></button></div>}

 <div className="vision-layout"><section className="video-panel surface"><div className="section-title"><div><Camera size={18}/><h2>AEGIS live road feed</h2></div><div className="view-switch"><button className={!view?'active':''} onClick={()=>setView(false)}>Minimal</button><button className={view?'active':''} onClick={()=>setView(true)}>Intelligence</button></div></div>
 <div className={`live-stage ${drag?'dragging':''}`} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);const f=e.dataTransfer.files[0];if(f)void upload(f)}}>
 {(video||camera)?<><LiveCanvas packet={frame} intelligence={view} preview={video?`/api/videos/${video.id}/thumbnail`:undefined} onRendered={rendered} isCurrent={p=>p.generation===generation.current}/>{!packet&&<div className="live-stage-message">{status==='initializing'||status==='connecting'?<><LoaderCircle className="spin" size={28}/><b>Initializing live perception</b><span>The source clock starts when models are ready.</span></>:<><Play size={30}/><b>{camera?'Camera connected':'Video connected'}</b><span>Press Play to start live AI.</span></>}</div>}</>:<button className="live-upload-placeholder" onClick={()=>file.current?.click()}><Upload size={34}/><b>Drop a road video here</b><span>Or connect a camera. Play starts the AI.</span></button>}
 </div>
 <div className="live-controls"><button className="play-control" aria-label={busy?'Pause':'Play'} disabled={!video&&!camera||uploading} onClick={()=>busy?pause():void play()}>{busy?<Pause size={20}/>:<Play size={20}/>}</button><button className="icon-button" aria-label="Stop" disabled={!session} onClick={stop}><Square size={17}/></button><time>{time.toFixed(1)}s</time>{video&&<><input aria-label="Seek video" type="range" min="0" max={video.info.durationSeconds} step=".1" value={time} disabled={!session} onChange={e=>setSeekValue(Number(e.target.value))} onPointerUp={e=>seek(Number(e.currentTarget.value))} onKeyUp={e=>seek(Number(e.currentTarget.value))}/><time>{video.info.durationSeconds.toFixed(1)}s</time></>}{camera&&<span className="camera-source">● CAMERA STREAM</span>}</div>
 <div className="video-bottom"><div className="video-info"><FileVideo size={17}/><div><b>{video?.info.filename||(camera?(cameraSource==='configured'?'Configured CCTV camera':'Browser camera'):'No source connected')}</b><small>{packet?`Segment ${packet.segment} · frame ${packet.frameNumber} · synchronized image + AI`:'PLAY starts · PAUSE freezes · SEEK resets local tracking'}</small></div></div><span className="mode-badge">{mode}</span></div>

 {developer&&packet&&<div className="performance-monitor"><span>SOURCE {packet.performance.sourceFPS??'camera'} FPS</span><span>INFERENCE {packet.performance.processingFPS} FPS</span><span>DISPLAY {displayFPS} FPS</span><span>INFERENCE {packet.performance.inferenceLatencyMs} ms</span><span>STREAM {packet.performance.streamLatencyMs} ms</span><span>DROPPED {packet.performance.droppedFrames}</span><span>{packet.performance.device.toUpperCase()} · {packet.adaptiveCompute?'ADAPTIVE':'NORMAL'}</span></div>}
 </section><Understanding intelligence={intelligence} metrics={packet?.metrics} busy={busy} status={status}/></div>
 <section className="transcript-panel surface"><div className="section-title"><div><History size={17}/><h2>Live transcript</h2><span className="transcript-count">{events.length} events</span></div><div className="view-switch">{['ALL','IMPORTANT','CRITICAL'].map(value=><button key={value} className={filter===value?'active':''} onClick={()=>setFilter(value)}>{value.charAt(0)+value.slice(1).toLowerCase()}</button>)}</div></div>{shown.length?<div className="live-transcript">{shown.slice(-20).map(event=><article className={`transcript-event ${event.severity.toLowerCase()}`} key={event.eventId}><button className="transcript-moment" onClick={()=>seek(event.timestampSeconds)}><time>{timestamp(event.timestampSeconds)}</time><div><span className="event-severity">{event.severity}</span><b>{event.title||event.eventType}</b><span className="transcript-context">{event.description}</span></div></button>{event.evidence.event&&<button className="snapshot-button" onClick={()=>setSelected(event)}><img src={event.evidence.event.image} alt={`${event.title} visual evidence`}/><span>View evidence →</span></button>}{!event.evidence.event&&<button className="transcript-details-button" onClick={()=>setSelected(event)}>Details</button>}</article>)}</div>:<div className="timeline-empty"><History size={24}/><span>{events.length?'No important events yet. Select All to see routine road observations.':'Meaningful changes appear here while the source plays.'}</span></div>}</section>
 {packet&&<details className="traffic-history surface"><summary>Traffic history</summary><RoadTimeline timeline={packet.timeline} events={[]} onSeek={seek}/></details>}
 {session&&events.length>0&&<section className="report surface"><div className="section-title"><div><Shield size={17}/><h2>{status==='ended'?'Playback report':'Live event memory'}</h2></div><span>{events.length} recorded changes</span></div><div className="report-content"><div className="report-text"><b>{status==='ended'?'Observed road story':'Observations saved as you watch'}</b><span>Evidence and transcript are saved during playback.</span><small>Sampled observations · skipped frames and seeks leave gaps</small></div><div className="downloads"><a href={`/api/live/${session}/export/json`} download><Download size={15}/> Report JSON</a><a href={`/api/live/${session}/export/transcript`} download><Download size={15}/> Transcript</a><a href={`/api/live/${session}/print`} target="_blank" rel="noreferrer"><Download size={15}/> Print / PDF</a></div></div></section>}
 {selectedEvent&&<div className="evidence-modal" role="dialog" aria-modal="true" aria-label="Event visual evidence"><section className="surface"><div className="section-title"><div><Camera size={18}/><h2>{selectedEvent.title}</h2></div><button className="icon-button" aria-label="Close evidence" onClick={()=>setSelected(null)}><X size={20}/></button></div><div className="evidence-modal-body"><p>{selectedEvent.description}</p><div className="evidence-gallery">{['before','event','after'].filter(role=>selectedEvent.evidence[role]).map(role=><figure key={role}><img src={selectedEvent.evidence[role].image} alt={`${role} evidence`}/><figcaption>{role.toUpperCase()} · {selectedEvent.evidence[role].timestampSeconds?.toFixed(2)}s</figcaption><small>{selectedEvent.evidence[role].whyThisFrame}</small><a href={selectedEvent.evidence[role].raw} target="_blank" rel="noreferrer">Original frame</a></figure>)}</div>{selectedEvent.clip&&<p><a href={selectedEvent.clip.url} download>Download original incident clip</a></p>}<h3>Observed evidence</h3><ul>{evidenceLines(selectedEvent.observed).map((line,index)=><li key={index}>{line}</li>)}</ul><h3>Event story</h3><ol>{selectedEvent.story.slice(-8).map((moment,index)=><li key={index}><time>{moment.time.toFixed(2)}s</time> · {moment.description}</li>)}</ol><p>Interpretation: {selectedEvent.inference}</p><p>{selectedEvent.confidence==null?'No calibrated incident confidence available.':selectedEvent.confidenceType==='visual similarity'?`Visual match: ${selectedEvent.confidence.toFixed(2)}`:`Detector score: ${Math.round(selectedEvent.confidence*100)}%`}</p><p>Emergency-access estimate: {selectedEvent.emergencyAccess}/100 · experimental</p><p>{selectedEvent.recommendation}</p><button className="primary" onClick={()=>{seek(Math.max(0,selectedEvent.timestampSeconds-2));void play()}}><Play size={15}/> Replay observed moment</button></div></section></div>}
 </main><footer><span><Shield size={13}/> AEGIS · Live vision & event intelligence</span><span>LIVE VISION ENGINE / v3.0</span></footer></div>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
