import Constants from 'expo-constants';
import * as SecureStore from 'expo-secure-store';
export type Role='Citizen'|'Ambulance Driver'|'Paramedic'|'Hospital Staff'|'Traffic Officer'|'Emergency Operator'|'Administrator';
export type User={id:string;name:string;email:string;role:Role};
export type Hospital={id:string;name:string;district:string;distance:number;eta:number;icu:number;load:number;specialist:boolean;trauma:boolean;x:number;y:number;resources:{id:string;type:string;status:string}[]};
export type Emergency={id:string;owner:string;name:string;age:number;type:string;priority:string;status:string;created:number;ambulance:string;hospital:string;route:string;progress:number;reroutes:number;eta:number;normalEta:number;optimizedEta:number;readiness:number;vitals:{hr:number;spo2:number;bp:string;consciousness:string;bleeding:string};timeline:{time:number;text:string;kind:string}[];observations:string[];x:number;y:number};
export type AegisState={emergencies:Emergency[];hospitals:Hospital[];ambulances:{id:string;status:string;equipment:string;eta:number;x:number;y:number}[];signals:{id:string;state:string;density:number;mode:string;blocked:boolean;x:number;y:number}[];roads:{id:string;density:number;blocked:boolean}[];incidents:{id:string;type:string;x:number;y:number}[];weights:number[];disaster:boolean;network:boolean;demoStart:number|null;demoStep:number;notifications:{id:string;message:string;time:number}[];history:number[];mass:{hospital:string;patients:number}[];revision?:number};
export const apiOrigin=String(Constants.expoConfig?.extra?.apiUrl||'').replace(/\/$/,'');const SERVER='aegis.api.origin';export async function currentApiOrigin(){return (await SecureStore.getItemAsync(SERVER)||apiOrigin).replace(/\/$/,'');}export async function setApiOrigin(value:string){const url=new URL(value);if(!['https:','http:'].includes(url.protocol)||url.username||url.password||url.pathname!=='/'||url.search||url.hash)throw Error('Enter the AEGIS API origin only, such as https://your-api.example.com');if(url.protocol==='http:'&&!/^(localhost|127(?:\.\d{1,3}){3}|10(?:\.\d{1,3}){3}|192\.168(?:\.\d{1,3}){2}|172\.(?:1[6-9]|2[0-9]|3[01])(?:\.\d{1,3}){2})$/.test(url.hostname))throw Error('HTTP is permitted for local development addresses. Use HTTPS for a remote server.');await SecureStore.setItemAsync(SERVER,url.origin,{keychainAccessible:SecureStore.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY});}
const TOKEN='aegis.native.jwt';
export const token=()=>SecureStore.getItemAsync(TOKEN);
export async function saveToken(value:string){await SecureStore.setItemAsync(TOKEN,value,{keychainAccessible:SecureStore.AFTER_FIRST_UNLOCK_THIS_DEVICE_ONLY});}
export const clearToken=()=>SecureStore.deleteItemAsync(TOKEN);
export async function api<T>(path:string,body?:unknown){const origin=await currentApiOrigin();if(!origin)throw Error('Set an AEGIS API address in the app settings.');const jwt=await token();let response:Response;try{response=await fetch(origin+path,{method:body?'POST':'GET',headers:{Accept:'application/json',...(body?{'Content-Type':'application/json'}:{}),...(jwt?{Authorization:`Bearer ${jwt}`}:{})},body:body?JSON.stringify(body):undefined});}catch{throw Error('AEGIS is unreachable. Connect to an authorized server URL and try again.');}const content=response.headers.get('content-type')||'';if(!content.includes('application/json'))throw Error('This server did not return AEGIS data. Set EXPO_PUBLIC_AEGIS_API_URL to an authorized AEGIS API server.');const data=await response.json() as T&{error?:string};if(!response.ok)throw Error(data.error||'AEGIS could not complete that request.');return data;}
export function isMapConfigured(platform:'ios'|'android'|'web'){if(platform==='ios')return Constants.expoConfig?.extra?.iosMapsReady===true;if(platform==='android')return Constants.expoConfig?.extra?.androidMapsReady===true;return false;}
export const CATEGORIES=['Road accident','Cardiac','Breathing Emergency','Fire/Burn','Pregnancy','Stroke','Injury','Other'];
