import { useEffect, useMemo, useRef, useState } from 'react';
import { AlertTriangle, Ambulance, CheckCircle2, ChevronRight, CircleDot, Crosshair, LocateFixed, MapPinned, Navigation, Radio, RefreshCw, Route as RouteIcon, ShieldCheck, Siren, Timer, TriangleAlert, WifiOff } from 'lucide-react';
import { controlRoomGateway } from './api';
import type { Candidate, EmergencySnapshot, FailureMode } from './domain';
import { interpolate, observationFromTelemetry } from './interpolation';
import { GoogleMapCanvas } from './GoogleMapCanvas';

const gateway = controlRoomGateway();
const missionId = 'EM-2026-001';
const idempotency = () => crypto.randomUUID();
const seconds = (value?: number) => value == null ? '—' : `${Math.ceil(value / 60)} min`;
const distance = (value?: number) => value == null ? '—' : `${(value / 1000).toFixed(1)} km`;
const age = (value?: string) => !value ? 'Unknown' : `${Math.max(0, Math.floor((Date.now() - Date.parse(value)) / 1000))}s ago`;

function App() {
  const [snapshot, setSnapshot] = useState<EmergencySnapshot>();
  const [selected, setSelected] = useState<string>('AMB-B');
  const [message, setMessage] = useState<string>();
  const [pending, setPending] = useState(false);
  const [filter, setFilter] = useState<'ALL' | 'ELIGIBLE' | 'EXCLUDED'>('ALL');
  useEffect(() => { let active = true; gateway.getSnapshot(missionId).then((value) => active && setSnapshot(value)).catch((error) => active && setMessage(error.message)); const subscription = gateway.subscribe(missionId, (event) => { if (!active) return; if (event.type === 'snapshot.updated') setSnapshot((current) => !current || event.entityVersion >= current.entityVersion ? event.snapshot : current); if (event.type === 'connection.state') setMessage('Connection is reconnecting — the last authoritative snapshot remains visible.'); }); return () => { active = false; subscription.close(); }; }, []);
  const selectedCandidate = snapshot?.candidates.find((item) => item.ambulance.ambulanceId === (snapshot.assignment?.ambulanceId ?? selected));
  const perform = async (task: () => Promise<EmergencySnapshot>) => { setPending(true); setMessage(undefined); try { const next = await task(); setSnapshot(next); } catch (error) { setMessage(error instanceof Error ? error.message : 'The server did not confirm this action.'); } finally { setPending(false); } };
  if (!snapshot) return <main className="loading"><Siren size={32}/><div><strong>Opening AEGIS command center</strong><span>Retrieving an authoritative mission snapshot…</span></div></main>;
  const visible = snapshot.candidates.filter((candidate) => filter === 'ALL' || (filter === 'ELIGIBLE' ? candidate.eligible : !candidate.eligible));
  return <main className="app-shell">
    <header className="topbar"><div className="brand"><span className="brand-mark"><ShieldCheck size={19}/></span><span>AEGIS</span><small>Emergency intelligence network</small></div><div className="top-status"><span className="simulation"><Radio size={13}/> SIMULATION</span><span className={snapshot.providerHealth.routing === 'HEALTHY' ? 'health healthy' : 'health risk'}><CircleDot size={13}/> Routing {snapshot.providerHealth.routing.toLowerCase()}</span><span className="identity">OPERATOR · LOCAL DEMO</span></div></header>
    <section className="command-grid">
      <aside className="incident-rail panel"><div className="rail-heading"><span>Active incident</span><button className="icon-button" aria-label="Refresh authoritative snapshot" onClick={() => perform(() => gateway.getSnapshot(snapshot.emergencyId))}><RefreshCw size={16}/></button></div><div className="emergency-id"><span>108 · {snapshot.emergencyId}</span><strong>{snapshot.urgency}</strong></div><div className="state-row"><span className="pulse"/> {snapshot.state.replaceAll('_', ' ')}</div><hr/><section><label>Confirmed pickup</label><h2>{snapshot.pickup.address}</h2><p>{snapshot.pickup.landmark}</p><dl><div><dt>Source</dt><dd>{snapshot.pickup.source.replaceAll('_', ' ')}</dd></div><div><dt>Accuracy</dt><dd>±{snapshot.pickup.accuracyMeters ?? '—'} m</dd></div><div><dt>Captured</dt><dd>{age(snapshot.pickup.capturedAt)}</dd></div></dl></section><div className={`uncertainty ${snapshot.pickup.confirmationStatus === 'CONFIRMED' ? 'confirmed' : ''}`}><MapPinned size={17}/><span><strong>{snapshot.pickup.confirmationStatus}</strong><br/>{snapshot.pickup.accessInstructions || 'No access instructions recorded.'}</span></div><button className="secondary full" disabled={pending} onClick={() => { const address = window.prompt('Corrected address', snapshot.pickup.address); if (!address) return; void perform(() => gateway.correctPickup(snapshot.emergencyId, { entityVersion: snapshot.entityVersion, address, coordinates: snapshot.pickup.coordinates, accuracyMeters: snapshot.pickup.accuracyMeters, accessInstructions: snapshot.pickup.accessInstructions, justification: 'Operator corrected pickup after verification.' })); }}><MapPinned size={16}/> Correct pickup</button><hr/><section><label>Confirmed response requirements</label><div className="chips">{[...snapshot.requiredEquipment, ...snapshot.requiredCrewCapabilities, snapshot.requiredCapacity].map((item) => <span key={item}>{item.replaceAll('_', ' ')}</span>)}</div><p className="fine-print">Requirements are operator-confirmed inputs. AEGIS does not diagnose or infer them.</p></section></aside>
      <section className="map-panel panel"><div className="map-toolbar"><div><span className="eyebrow">Live fleet view</span><strong>Patient pickup & nearby ambulances</strong></div><div className="map-actions"><button aria-label="Center patient pickup"><Crosshair size={16}/> Patient</button><button aria-label="Fit fleet and patient"><LocateFixed size={16}/> Fit fleet</button></div></div><MapAdapter snapshot={snapshot} selected={snapshot.assignment?.ambulanceId ?? selected}/><div className="map-footer"><span><i className="dot pickup"/> Confirmed pickup</span><span><i className="dot ready"/> Available & fresh</span><span><i className="dot selected"/> Assigned / selected</span><span><i className="dot stale"/> Stale or unavailable</span><span className="camera-note">Camera is operator-controlled</span></div></section>
      <aside className="dispatch-rail panel"><div className="rail-heading"><div><span>Dispatch board</span><strong>{snapshot.candidates.filter((item) => item.eligible).length} suitable</strong></div><div className="segmented">{(['ALL','ELIGIBLE','EXCLUDED'] as const).map((item) => <button key={item} className={filter === item ? 'active' : ''} onClick={() => setFilter(item)}>{item}</button>)}</div></div><div className="candidate-list">{visible.map((candidate) => <CandidateCard key={candidate.ambulance.ambulanceId} candidate={candidate} selected={selected === candidate.ambulance.ambulanceId || snapshot.assignment?.ambulanceId === candidate.ambulance.ambulanceId} onSelect={() => setSelected(candidate.ambulance.ambulanceId)}/>)}</div>{selectedCandidate && !snapshot.assignment && <div className="dispatch-footer"><div><small>Selected vehicle</small><strong>{selectedCandidate.ambulance.callSign} · {seconds(selectedCandidate.roadEtaSeconds)}</strong></div><button className="dispatch" disabled={!selectedCandidate.eligible || pending} onClick={() => void perform(() => gateway.dispatch(snapshot.emergencyId, { ambulanceId: selectedCandidate.ambulance.ambulanceId, entityVersion: snapshot.entityVersion, idempotencyKey: idempotency() }))}><Siren size={18}/> {pending ? 'Confirming…' : 'Dispatch ambulance'}</button></div>}{snapshot.assignment && <div className="confirmed-assignment"><CheckCircle2 size={20}/><div><span>Server-confirmed assignment</span><strong>{snapshot.assignment.ambulanceId}</strong><small>Direct dispatch — no driver acceptance is required.</small></div></div>}</aside>
    </section>
    {message && <div className="toast"><TriangleAlert size={17}/>{message}<button onClick={() => setMessage(undefined)}>×</button></div>}
    <section className="mission-strip panel"><div className="mission-status"><span className="eyebrow">Assignment assurance</span><AssignmentProgress snapshot={snapshot}/>{snapshot.assignment && <button className="text-button" onClick={() => { const replacement=snapshot.candidates.find((item)=>item.eligible&&item.ambulance.ambulanceId!==snapshot.assignment?.ambulanceId); const reason=window.prompt('Reason for authorized reassignment'); if(!reason)return; if(!replacement){setMessage('No alternate eligible vehicle is currently available. Escalate instead of reducing requirements.');return;} void perform(()=>gateway.reassign(snapshot.emergencyId,{ambulanceId:replacement.ambulance.ambulanceId,entityVersion:snapshot.entityVersion,reason,idempotencyKey:idempotency()})); }}>Authorized reassignment</button>}</div><div className="timeline"><span className="eyebrow">Mission timeline</span>{snapshot.timeline.slice(0, 3).map((item) => <div key={item.eventId}><i/><span>{item.label.replaceAll('.', ' ')}</span><small>{age(item.occurredAt)}</small></div>)}</div><div className="alerts"><span className="eyebrow">Operations alerts</span>{snapshot.alerts.length ? snapshot.alerts.map((alert) => <p key={alert.alertId} className={alert.level.toLowerCase()}><AlertTriangle size={15}/>{alert.label}</p>) : <p className="clear"><CheckCircle2 size={15}/> No active escalation</p>}</div><div className="failure-menu"><span className="eyebrow">Demo controls</span><select aria-label="Inject deterministic demo failure" defaultValue="NONE" onChange={(event) => void perform(() => gateway.injectFailure(snapshot.emergencyId, { mode: event.target.value as FailureMode }))}><option value="NONE">Clear injected failure</option><option value="ROUTING_OUTAGE">Routing outage</option><option value="DRIVER_OFFLINE">Driver app offline</option><option value="ACKNOWLEDGEMENT_TIMEOUT">Acknowledgement timeout</option><option value="GPS_DISABLED">GPS disabled</option><option value="STALE_TELEMETRY">Stale GPS</option><option value="NETWORK_LOSS">Network loss</option><option value="EQUIPMENT_FAILURE">Equipment failure</option></select><button className="text-button" onClick={() => void perform(() => gateway.resetDemo())}>Reset demonstration</button></div></section>
  </main>;
}

function CandidateCard({ candidate, selected, onSelect }: { candidate: Candidate; selected: boolean; onSelect: () => void }) { const telemetry = candidate.ambulance.telemetry; return <button className={`candidate ${selected ? 'selected' : ''} ${!candidate.eligible ? 'excluded' : ''}`} onClick={onSelect}><span className={`vehicle-status ${candidate.ambulance.status.toLowerCase()}`}><Ambulance size={18}/></span><span className="candidate-body"><span className="candidate-top"><strong>{candidate.ambulance.callSign}</strong>{candidate.eligible ? <b>{seconds(candidate.roadEtaSeconds)}</b> : <em>Excluded</em>}</span><span className="candidate-meta">{candidate.eligible ? `${distance(candidate.roadDistanceMeters)} · ${candidate.etaSource.replaceAll('_', ' ')}` : candidate.exclusionReasons?.[0]}</span><span className="candidate-caps">{candidate.ambulance.capabilities.slice(0, 2).map((item) => <i key={item}>{item.replaceAll('_', ' ')}</i>)}<small>{telemetry?.freshness === 'LIVE' ? `Live · ${age(telemetry.capturedAt)}` : 'Stale telemetry'}</small></span></span><ChevronRight size={16}/></button>; }
function AssignmentProgress({ snapshot }: { snapshot: EmergencySnapshot }) { const assignment = snapshot.assignment; const stages = [{ label: 'Backend confirmed', done: !!assignment }, { label: 'App receipt', done: !!assignment?.receivedAt }, { label: 'Driver acknowledgement', done: !!assignment?.acknowledgedAt }, { label: 'En route', done: !!assignment?.enRouteAt }]; return <div className="progress-row">{stages.map((stage, index) => <div className={stage.done ? 'done' : ''} key={stage.label}><span>{stage.done ? <CheckCircle2 size={16}/> : index + 1}</span><small>{stage.label}</small></div>)}{assignment && !assignment.acknowledgedAt && <p><Timer size={14}/> Acknowledgement due {age(assignment.acknowledgementDeadline)}</p>}</div>; }
function MapAdapter({ snapshot, selected }: { snapshot: EmergencySnapshot; selected: string }) { return import.meta.env.VITE_GOOGLE_MAPS_BROWSER_KEY ? <GoogleMapCanvas snapshot={snapshot} selected={selected}/> : <OperationsMap snapshot={snapshot} selected={selected}/>; }
function OperationsMap({ snapshot, selected }: { snapshot: EmergencySnapshot; selected: string }) { const histories = useRef(new Map<string, ReturnType<typeof observationFromTelemetry>[]>()); const [frame, setFrame] = useState(Date.now()); useEffect(() => { snapshot.candidates.forEach((candidate) => { const telemetry = candidate.ambulance.telemetry; if (!telemetry) return; const history = histories.current.get(candidate.ambulance.ambulanceId) ?? []; const observation = observationFromTelemetry(telemetry); if (history.at(-1)?.capturedAt !== observation.capturedAt) histories.current.set(candidate.ambulance.ambulanceId, [...history.slice(-3), observation]); }); }, [snapshot]); useEffect(() => { if (window.matchMedia('(prefers-reduced-motion: reduce)').matches) return; const timer = window.setInterval(() => setFrame(Date.now()), 80); return () => window.clearInterval(timer); }, []); const project = (latitude: number, longitude: number) => ({ left: `${40 + (longitude - 77.5946) * 2600}%`, top: `${52 - (latitude - 12.9716) * 2600}%` }); const route = snapshot.assignment?.route; return <div className="operations-map" role="img" aria-label="Simulation map showing confirmed patient pickup and nearby ambulance locations"><div className="street street-a"/><div className="street street-b"/><div className="street street-c"/>{route?.geometry && <svg className="route-line" viewBox="0 0 100 100" preserveAspectRatio="none"><path d="M 25 67 C 42 62, 54 45, 62 49"/></svg>}<div className="pickup-pin" style={project(snapshot.pickup.coordinates!.latitude, snapshot.pickup.coordinates!.longitude)}><MapPinned size={28}/><span>Pickup</span></div>{snapshot.candidates.map((candidate) => { const telemetry = candidate.ambulance.telemetry; if (!telemetry) return null; const position = interpolate(histories.current.get(candidate.ambulance.ambulanceId) ?? [], frame) ?? telemetry.coordinates; return <button key={candidate.ambulance.ambulanceId} className={`map-ambulance ${candidate.ambulance.ambulanceId === selected ? 'focused' : ''} ${telemetry.freshness === 'STALE' ? 'stale' : ''}`} style={project(position.latitude, position.longitude)} aria-label={`${candidate.ambulance.callSign}, ${candidate.ambulance.status}`}><Ambulance size={18}/><span>{candidate.ambulance.callSign.replace('AMB-', '')}</span></button>; })}<div className="simulation-watermark">SIMULATION · DEMO MAP ADAPTER</div></div>; }
export default App;
